[package]
name = "bls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = "0.4.0"
ark-ec = "0.4.1"
ark-std = "0.4"
rand = "0.8.5"

[[bin]]
name = "binary"
path = "src/lib.rs"